@echo off
echo Starting Backend Server...
start cmd /k "cd backend && npm run server"

echo Starting Frontend Server...
start cmd /k "cd frontend && npm run dev"

echo Waiting for servers to start...
timeout /t 3 /nobreak >nul

echo Opening launcher...
start launcher.html
